linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec

linters-settings:
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G404 # Insecure random number source (rand)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: internal/util/jwt.go
      text: 'G401: Crypto primitive'
      linters:
        - gosec
  exclude-dirs:
    - vendor/

run:
  timeout: 5m
  tests: true
