// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (sql.Result, error)
	DeletePasswordReset(ctx context.Context, token string) error
	GetPasswordResetByToken(ctx context.Context, token string) (GetPasswordResetByTokenRow, error)
	SearchUsers(ctx context.Context, arg SearchUsersParams) ([]User, error)
}

var _ Querier = (*Queries)(nil)
